services:
  server:
    image: phonebook-backend-prod
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=MONGOURL
      - PORT=3001
    volumes:
      - ./backend/:/usr/src/app
    container_name: phonebook-server-prod
  app:
    image: phonebook-frontend-prod
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    container_name: phonebook-frontend-prod
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-reverse-proxy
    depends_on:
      - server
      - app
